In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7212, 3295, 1486, 3406],
 [7212, 3295, 1486, 8886],
 [7212, 7136, 1486, 6472],
 [7655, 9647, 6486, 5832, 4628],
 [7655, 9647, 6486, 5832, 4154],
 [314, 7212, 5277, 1486, 5042],
 [6119, 4588, 1604, 5832]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7212 3295 1486 3406]
 [   0    0    0    0 7212 3295 1486 8886]
 [   0    0    0    0 7212 7136 1486 6472]
 [   0    0    0 7655 9647 6486 5832 4628]
 [   0    0    0 7655 9647 6486 5832 4154]
 [   0    0    0  314 7212 5277 1486 5042]
 [   0    0    0    0 6119 4588 1604 5832]]


In [15]:
## feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/mnt/d/gemini/ai/sentiment-analysis/.venv/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-11-06 10:21:31.023620: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-11-06 10:21:31.409045: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 386ms/step


array([[[ 0.02151897,  0.03652919, -0.02668489,  0.01191377,
         -0.01949897, -0.01045786, -0.02470915,  0.04323764,
         -0.03449925, -0.01813511],
        [ 0.02151897,  0.03652919, -0.02668489,  0.01191377,
         -0.01949897, -0.01045786, -0.02470915,  0.04323764,
         -0.03449925, -0.01813511],
        [ 0.02151897,  0.03652919, -0.02668489,  0.01191377,
         -0.01949897, -0.01045786, -0.02470915,  0.04323764,
         -0.03449925, -0.01813511],
        [ 0.02151897,  0.03652919, -0.02668489,  0.01191377,
         -0.01949897, -0.01045786, -0.02470915,  0.04323764,
         -0.03449925, -0.01813511],
        [ 0.00916562, -0.00518229, -0.02333599,  0.03074051,
          0.01938384,  0.02964019, -0.04861743,  0.04407502,
         -0.03319059,  0.03597322],
        [-0.00161085,  0.03606826, -0.04494114, -0.03659216,
          0.02361227,  0.00675379,  0.02298402, -0.00084972,
          0.04847637, -0.01724243],
        [-0.03223115,  0.02376087,  0.02704399,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531